"""Authentication package: magic-link sign-in, JWT/session state, and RBAC."""

from .auth import (
    get_current_access_token,
    get_current_refresh_token,
    get_current_user_email,
    get_current_user_id,
    get_current_user_profile,
    get_current_user_role,
    get_or_create_session_id,
    has_role,
    init_auth,
    is_admin,
    is_editor,
    is_signed_in,
    list_past_chats,
    refresh_access_token_if_needed,
    request_magic_link,
    set_auth_tokens,
    sign_out,
    start_new_chat,
    switch_to_session,
    verify_magic_link_token,
)

__all__ = [
    "get_current_access_token",
    "get_current_refresh_token",
    "get_current_user_email",
    "get_current_user_id",
    "get_current_user_profile",
    "get_current_user_role",
    "get_or_create_session_id",
    "has_role",
    "init_auth",
    "is_admin",
    "is_editor",
    "is_signed_in",
    "list_past_chats",
    "refresh_access_token_if_needed",
    "request_magic_link",
    "set_auth_tokens",
    "sign_out",
    "start_new_chat",
    "switch_to_session",
    "verify_magic_link_token",
]
